### PR TITLE
switched positions of  duration and number of units indicators in ho…

### PR DESCRIPTION
**Pull request by YupengLei**
switched positions of  duration and number of units indicators in homepage

### CODE REVIEW

**Comment by jdomindev** [comment]
Just need to switch the order of the event indicators on the homepage

**Comment by YupengLei** [comment]
> 

yes, it is switched on my local, it doesn't work?

**Comment by jdomindev** [comment]
You have to push the changes to your remote branch

**Comment by YupengLei** [comment]
> You have to push the changes to your remote branch

??? I pushed already, this is my PR, I'm confused...

**Comment by jdomindev** [comment]
I only see the changes to the education indicators, not the events. So you have to push the additional changes on your branch to update the pull request.

**Comment by YupengLei** [comment]
> I only see the changes to the education indicators, not the events. So you have to push the additional changes on your branch to update the pull request.

I did not change education indicators, I changed the housing indicators, I am really confused, can you screen shot the problem?

**Comment by jdomindev** [comment]
> > I only see the changes to the education indicators, not the events. So you have to push the additional changes on your branch to update the pull request.
> 
> I did not change education indicators, I changed the housing indicators, I am really confused, can you screen shot the problem?
> 
> I meant housing, that is my fault. We just need the events indicators' order to be switched just like you did for the housing indicators.



> > I only see the changes to the education indicators, not the events. So you have to push the additional changes on your branch to update the pull request.
> 
> I did not change education indicators, I changed the housing indicators, I am really confused, can you screen shot the problem?


I meant housing, that is my fault. We just need the events indicators' order to be switched just like you did for the housing indicators.

**Review by jdomindev — APPROVED** [review]

**Pull request merged**
